server:
  port: 8182

spring:
  application:
    name: hello-mybatis-uc-apiserver

  datasource:
    url: jdbc:mysql://192.168.31.3:20041/ljz_grky_dev?useSSL=false&serverTimezone=Asia/Shanghai
    username: mysql
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.study.hello.distributed.mybatis.apiserver.entity
# 可以添加其他测试特定的配置
logging:
  level:
    root: INFO
    com.study.hello.distributed.mybatis.demo: DEBUG
jwt:
  secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  expiration: 86400
